from collections.abc import Callable as Callable
from typing import Any, Generic, NoReturn, ParamSpec, TypeVar

T = TypeVar("T")
P = ParamSpec("P")

class reduce(Generic[P, T]):
    __wrapped__: Callable[P, T]
    def __init__(self, func: Callable[P, T]) -> None: ...
    def install(self, *args: P.args, **kwargs: P.kwargs) -> dict[str, Any]: ...
    def __call__(self, /, kwds: dict[str, Any]) -> T: ...
    @property
    def args(self) -> tuple[str, ...]: ...
    @args.setter
    def args(self, value: tuple[str, ...]) -> NoReturn: ...
    @property
    def kwargs(self) -> tuple[str, ...]: ...
    @kwargs.setter
    def kwargs(self, value: tuple[str, ...]) -> NoReturn: ...
